### ISSUE TITLE
Loading page status

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-elm#36]
The api and auth service application are currently hosted on a free Heroku dyno. So when the application is sending some request (e.g auth page, capture page) a blank page is displayed with only the dwyl logo  while the Heroku applications are waking up:
![image](https://user-images.githubusercontent.com/6057298/78253614-96d70800-74ec-11ea-9584-a07ae2824d0e.png)

We can let the user know that the page is still loading by using a loader/spinner.
[elm-animator](https://github.com/mdgriffith/elm-animator) is currently a work in progress so I might not try to include it in the application yet.
Instead I'll try to build an elm-ui element similar to https://www.w3schools.com/howto/howto_css_loader.asp

**Comment by SimonLab** [comment]
I've manage to create the following loader:
![laoder](https://user-images.githubusercontent.com/6057298/78260349-c76f6f80-74f5-11ea-88ad-918b4aa1a89f.gif)

Unfortunately the css is too specific to be able to implement it using only elm-ui defaul functions.
However we can convert normal elm html and css function to elm-ui using the [html](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element#html) function.

.1 Create an elm div with the `loader` class:
```elm
loaderHtml : Html.Html msg
loaderHtml =
    Html.div [HtmlAttr.class "loader"] []
```

.2 Create a css file which defined the `loader` class
```css
.loader {
    border: 16px solid #f3f3f3; /* Light grey */
    border-top: 16px solid #4BC0A9; /* Teal */
    border-radius: 50%;
    width: 100px;
    height: 100px;
    animation: spin 2s linear infinite;
  }
  
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
```
I've also imported this new css file to the `index.html` file:
```html
...
<link rel="stylesheet" href="/assets/css/main.css" /
```

.3 Add the loaderHtml function using `Element.html` function
```elm
el [centerX] <| html UI.loaderHtm
```
